

export const FETCH_MORE_LINKS =  'FETCH_MORE_LINKS';
export const FETCH_MORE_LINKS_SUCCESS =  'FETCH_MORE_LINKS_SUCCESS';
export const FETCH_MORE_LINKS_FAIL =  'FETCH_MORE_LINKS_FAIL';


export const GET_RELATED_TAGS_SUCCESS =  'GET_RELATED_TAGS_SUCCESS';


export const GET_RESPONSES =  'GET_RESPONSES';
export const GET_RESPONSES_SUCCESS =  'GET_RESPONSES_SUCCESS';
export const GET_RESPONSES_FAIL =  'GET_RESPONSES_FAIL';