

export const FETCH_MORE_LINKS =  'FETCH_MORE_LINKS';
export const FETCH_MORE_LINKS_SUCCESS =  'FETCH_MORE_LINKS_SUCCESS';
export const FETCH_MORE_LINKS_FAIL =  'FETCH_MORE_LINKS_FAIL';


export const GET_RELATED_TAGS_SUCCESS =  'GET_RELATED_TAGS_SUCCESS';